### ISSUE TITLE
Template validation error: Invalid template resource property 'name'

### ISSUE THREAD

**Issue by Akarthikesh** [asquarezone/AWSClassRoom#1]
i create a stack 
iam getting template validation error
that error is ->Template validation error: Invalid template resource property 'name'

my code is

{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "cf feb 2019",
  "Resources": {
    "ourvpc": {
      "name": "AWS::EC2::VPC",
      "Type": "Aws",
      "Properties": {
        "CidrBlock": "10.0.0.0/16",
        "Tags": [
          {
            "Key": "awsvpc",
            "Value": "overall"
          }
        ]
      }
    }
  }
}

**Comment by dharmatejadevops** [comment]
replace name with Type and remove the Type key on your code.
follow this for creating vpc 
"name": {
              "Type": "AWS::EC2::VPC",
              "Properties": {
                "CidrBlock": "----/--",
                "Tags": [-]
              }
            }

**Comment by sandhyadev** [comment]
Is this issue resolved

**Comment by jbryan3091** [comment]
I create this stack, have this problem : Template validation error: Invalid template resource property 'host'
{
  "Resources": {
    "Instancia1": {
        "Type": "AWS::EC2::Instance",
        "Properties": {
          "ImageId":"ami-1b2fa465",
          "KeyName": "key-AWS-Linux",
          "InstanceType" : "t3.micro",
          "SecurityGroupIds" :  ["sg-0df50ddc8ae357dfc"]
        },  
  
  "swagger": "2.0",
    "info": {
      "description": "Users API",
      "version": "1.0.0",
      "title": "Users"
    },

    "host": "api.users.es",
    "basePath": "/users",
    "schemes": [
      "http",
      "https"
    ],
    "produces": [
      "application/json"
    ],
    "consumes": [
      "application/json"
    ],
    "paths": {
      "/getusers": {
        "get": {
          "description": "Get all users",
          "responses": {
            "200": {
              "description": "OK",
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/user"
                }
              }
            }
          }
        }
      },
      "/createUsers": {
        "post": {
          "parameters": [
            {
              "in": "body",
              "name": "user",
              "schema": {
                "$ref": "#/definitions/user"
              },
              "required": true
            }
          ],
          "responses": {
            "201": {
              "description": "CREATED",
              "schema": {
                "$ref": "#/definitions/user"
              }
            },
            "405": {
              "description": "Invalid input"
            }
          }
        }
      },
      "/getusersById/{userId}": {
        "get": {
          "description": "Get one user",
          "parameters": [
            {
              "in": "path",
              "name": "userId",
              "type": "integer",
              "required": true
            }
          ],
          "responses": {
            "200": {
              "description": "OK",
              "schema": {
                "$ref": "#/definitions/user"
              }
            },
            "400": {
              "description": "Invalid user id"
            },
            "404": {
              "description": "User not found"
            }
          }
        }
      },
      "/updateUsersById/{userId}": {
        "put": {
          "parameters": [
            {
              "in": "path",
              "name": "userId",
              "type": "integer",
              "required": true
            },
            {
              "in": "body",
              "name": "user",
              "schema": {
                "$ref": "#/definitions/user"
              },
              "required": true
            }
          ],
          "responses": {
            "200": {
              "description": "OK",
              "schema": {
                "$ref": "#/definitions/user"
              }
            },
            "400": {
              "description": "Invalid user id"
            },
            "404": {
              "description": "User not found"
            }
          }
        }
      },
      "/deleteUsersById/{userId}": {
        "delete": {
          "parameters": [
            {
              "in": "path",
              "name": "userId",
              "type": "integer",
              "required": true
            }
          ],
          "responses": {
            "200": {
              "description": "OK"
            },
            "400": {
              "description": "Invalid user id"
            },
            "404": {
              "description": "User not found"
            }
          }
        }
      }
    },
    "definitions": {
      "user": {
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "birthDate": {
            "type": "string",
            "format": "LocalDateTime",
            "description": "LocalDateTime type"
          },
          "address": {
            "$ref": "#/definitions/address"
          }
        }
      },
      "address": {
        "properties": {
          "id": {
            "type": "integer"
          },
          "street": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "zip": {
            "type": "string"
          }
        }
      }
    }
}
}
}

**Comment by shaikkhajaibrahim** [comment]
Hi Bryan,
you have to strictly follow the syntax mentioned in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
I see some extra key elements. This will not be processed by amazon cloudformation

**Comment by jbryan3091** [comment]
Hi
shaikkhajaibrahim, sorry by the questions, I'm Systems Engenier, starting
in DevOps World because i'm applying for a scholarship place in a company
in Spain, so I've been required to do this following Challenge, which have
1 week as a deadline
2. Code Challenge
The tasks to be performed are the following:

● Generation of the node server using the swagger available at
https://s3-eu-west-1.amazonaws.com/mmi-codechallenge/swagger-users-v1.json
● Installing said server on an AWS machine
● Configure machine self-scaling and monitoring.
● Generation of a stress test script (using jmeter, postman or SOAPUi) to
verify that the machine scales.
● Sending the results.

On the other hand, it will be valued:

1) Installing the code using a ci (Continuous Integration) server (for
example, gitlab).
2) Use of the AWS API for machine creation (use cloudformation).
3) Use of technologies as ansible.

The development time is one week but much better if you can send it to us
before.

3. Delivery
It must be delivered:
1) Url with the application deployed.
2) Results of stress tests and jmeter.
3) Code used to deploy or generate the infrastructure.
4) Postman test

In this Way, I started to research last saturday, learning some concepts
about APIs, AWS services, Cloud Formatión, Js, Node js and so on, but I
believe that the key is experience which in my case is limited or nothing,
just for youtube videos or tutorial.

Finally, I'll be strongly gratefull to you, if you could give son guiandce
or avise.

greetings,

Jim Dios

**Comment by jschirad** [comment]
Hola, tengo el mismo problema, alguna solucione?
