### ISSUE TITLE
connecting EC2 machine

### ISSUE THREAD

**Issue by Divya-Moilla** [asquarezone/AWSClassRoom#11]
I con't connect to the ec2 machine by getting session time out error. how can it resolve
![Screenshot (11)](https://user-images.githubusercontent.com/51253159/61879903-890ac500-af11-11e9-82ce-4f59fcaf1791.png)

**Comment by sai2255** [comment]
change  user to your ec2 machine while connecting to host and try

**Comment by shaikkhajaibrahim** [comment]
You are connecting to Private IP Address. Connect to public ip
________________________________
