### ISSUE TITLE
VPC CLI issue 

### ISSUE THREAD

**Issue by SyedRaz** [asquarezone/AWSClassRoom#3]
An error occurred (VpcLimitExceeded) when calling the CreateVpc operation: The maximum number of VPCs has been reached.

Plz help me out

**Comment by sandhyadev** [comment]
Seems you already have 5 VPCs in your Region .
Default limit is 5 VPCs per Region  on aws account. 
Refer below link:
https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html
